### ISSUE TITLE
Vector2 ToString method not used in debugger

### ISSUE THREAD

**Issue by mcdirmid** [Microsoft/Win2D#184]
This is probably a more general problem with VS2015, but Vector2 instances never seemed to be blessed with their ToString representations in the debugger. This is incredibly inconvenient while debugging my win2d app. 

<img width="442" alt="capture" src="https://cloud.githubusercontent.com/assets/4374250/10744557/c03680f0-7c75-11e5-8a9b-3cf583f9aee7.PNG">

**Comment by damyanp** [comment]
Thanks for reporting this - this issue should be addressed in a future Visual Studio update.

**Comment by mcdirmid** [comment]
Just an update on this, this is still broken but seems to be related to a wider inability to display ToString or DebuggerDisplay attributes for structs under UWP. What does help: disable native builds (of course), and enable "Use Legacy C# and VB expression evaluators". Once this is done, Vector2 displays as expected (it still ignores struct tostring methods, but Vector2 seems to have a DebuggerDisplay attribute that works for me).

**Comment by shawnhar** [comment]
Yep, this is a broader issue in the Visual Studio debugger.  In fact the Vector2 type you are looking at isn't part of Win2D at all - this comes from the System.Vectors.Numerics NuGet package.

We confirmed that the Visual Studio team has an active internal bug tracking this problem.  I'm going to close this issue as it's not a Win2D problem.

Thanks for the report!

**Comment by mcdirmid** [comment]
Sounds good. Supposedly it will all be fixed in Update 2!
