### ISSUE TITLE
CanvasFontSet throws in Unpackaged apps

### ISSUE THREAD

**Issue by mattleibow** [microsoft/Win2D#891]
**Description**

I am trying to load a font in an unpackaged app:

```cs
using var fontSet = new CanvasFontSet(new Uri("ms-appx:///Fontawesome6brands.otf"));
```

This results in an exception:

```
System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet._ICanvasFontSetFactory.Create(Uri uri)
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet.<>c__DisplayClass11_0.<.ctor>b__0()
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet..ctor(Uri uri)
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile) in C:\Projects\maui\src\Core\src\Fonts\FontManager.Windows.cs:line 152
```

**Related Issues**

 - https://github.com/dotnet/maui/issues/9104

**Version Information**

```xml
<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.4" />
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.5" />
<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.194" />
```

**Reproduction Sample**

[App8.zip](https://github.com/microsoft/Win2D/files/9864179/App8.zip)

**Comment by SBProX** [comment]
I have the same issue when loading Font file

**Comment by SBProX** [comment]
It looks like it's a bug in the SDK when you try to use resources or content via ms-appx:///

I tried many possible options, specified the absolute path to the file, but ABI.System.Uri.СreateMarshaller(...) throws an exception, so I don't do it.

As soon as you make the application packaged, everything works.

**Comment by Redth** [comment]
Tracking in: https://dev.azure.com/microsoft/OS/_workitems/edit/43890883

**Comment by AllenD-MSFT** [comment]
@mattleibow This looks fixed. Can you close this issue?

**Comment by mattleibow** [comment]
This was fixed. Thanks!

**Comment by marossi7** [comment]
Hi

Was this actually fixed ? I still have the issue here with .NET 7 and WinAppSDK (1.5.240428000)
